// services/diagnosisService.js

// ======================================================
// AI-Assisted Urinary Stone Diagnosis Support Service
// ======================================================
//
// PURPOSE:
// This service converts YOLO detection results into
// AI-assisted preliminary interpretation output.
//
// IMPORTANT:
// - This is NOT a final medical diagnosis.
// - Results must always be reviewed by a doctor.
// - The system provides diagnosis SUPPORT only.
//
// ======================================================


// ======================================================
// Estimate Detection Region
// ======================================================
const estimateDetectionRegion = (bbox) => {

  /*
    Example bbox:

    {
      x: 120,
      y: 90,
      width: 45,
      height: 40
    }
  */

  if (!bbox) return 0;

  const width = Number(bbox.width || 0);
  const height = Number(bbox.height || 0);

  // Approximate detected area (NOT real medical size)
  const estimatedRegion = width * height;

  return Number(estimatedRegion.toFixed(2));
};


// ======================================================
// Generate AI Assessment Level
// ======================================================
const getAssessmentLevel = (regionValue) => {

  if (regionValue <= 0) {
    return 'No Significant Detection';
  }

  if (regionValue < 1000) {
    return 'Low Detection Probability';
  }

  if (regionValue >= 1000 && regionValue < 3000) {
    return 'Moderate Detection Probability';
  }

  return 'High Detection Probability';
};


// ======================================================
// Generate Recommendation
// ======================================================
const getRecommendation = (
  detected,
  assessmentLevel
) => {

  if (!detected) {

    return (
      'No obvious urinary stone was identified ' +
      'by the AI detection model. ' +
      'Clinical correlation and doctor review are recommended.'
    );

  }

  switch (assessmentLevel) {

    case 'Low Detection Probability':

      return (
        'A small suspicious region was identified. ' +
        'Clinical review and follow-up observation may be beneficial.'
      );

    case 'Moderate Detection Probability':

      return (
        'A possible urinary stone region was identified. ' +
        'Further medical evaluation or imaging review is recommended.'
      );

    case 'High Detection Probability':

      return (
        'A highly suspicious urinary stone region was identified. ' +
        'Specialist consultation is strongly recommended.'
      );

    default:

      return (
        'Further clinical evaluation is recommended.'
      );
  }
};


// ======================================================
// Generate AI Draft Text
// ======================================================
const generateAIDraft = ({
  detected,
  confidence,
  assessmentLevel,
  recommendation,
  stoneCount
}) => {

  const date = new Date().toLocaleDateString('en-GB');

  return `AI-ASSISTED PRELIMINARY RADIOLOGY REPORT
==================================================

Date of Analysis: ${date}

AI FINDINGS:
- Detection Status: ${detected ? 'Suspicious Stone Detected' : 'No Obvious Stone Detected'}
- Detection Confidence: ${confidence}%
- Detected Object Count: ${stoneCount}
- AI Assessment Level: ${assessmentLevel}

AI RECOMMENDATION:
${recommendation}

IMPORTANT DISCLAIMER:
This report is automatically generated by an AI-assisted urinary stone detection system.
It is intended only for preliminary clinical support purposes.
Final interpretation and diagnosis must be confirmed by a qualified medical professional.

==================================================`;
};


// ======================================================
// Main Diagnosis Generator
// ======================================================
const generateDiagnosis = (detectionResult) => {

  /*
    Expected Input Example:

    {
      detected: true,
      confidence: 0.91,
      stoneCount: 1,
      bbox: {
        x: 100,
        y: 80,
        width: 50,
        height: 40
      }
    }
  */

  // ====================================================
  // NO DETECTION
  // ====================================================
  if (
    !detectionResult ||
    detectionResult.detected === false
  ) {

    const assessmentLevel = 'No Significant Detection';

    const recommendation =
      getRecommendation(false, assessmentLevel);

    return {

      detected: false,

      confidence: 0,

      estimatedRegion: 0,

      stoneCount: 0,

      assessmentLevel,

      recommendation,

      status: 'no_obvious_stone',

      aiDraft: generateAIDraft({
        detected: false,
        confidence: 0,
        assessmentLevel,
        recommendation,
        stoneCount: 0
      }),

      disclaimer:
        'This output is AI-assisted and must be reviewed by a qualified medical professional.'
    };
  }


  // ====================================================
  // DETECTION EXISTS
  // ====================================================
  const confidence =
    Number(
      ((detectionResult.confidence || 0) * 100).toFixed(2)
    );

  const bbox =
    detectionResult.bbox || null;

  const stoneCount =
    detectionResult.stoneCount || 1;


  // ====================================================
  // Estimate Detection Region
  // ====================================================
  const estimatedRegion =
    estimateDetectionRegion(bbox);


  // ====================================================
  // Assessment Level
  // ====================================================
  const assessmentLevel =
    getAssessmentLevel(estimatedRegion);


  // ====================================================
  // Recommendation
  // ====================================================
  let recommendation =
    getRecommendation(true, assessmentLevel);


  // ====================================================
  // Low Confidence Warning
  // ====================================================
  if (confidence < 60) {

    recommendation +=
      ' Detection confidence is relatively low. ' +
      'Additional clinical review is recommended.';
  }


  // ====================================================
  // Final AI Draft
  // ====================================================
  const aiDraft =
    generateAIDraft({
      detected: true,
      confidence,
      assessmentLevel,
      recommendation,
      stoneCount
    });


  // ====================================================
  // Final Response
  // ====================================================
  return {

    detected: true,

    confidence,

    estimatedRegion,

    stoneCount,

    assessmentLevel,

    recommendation,

    status: 'pending_doctor_review',

    aiDraft,

    disclaimer:
      'This output is AI-assisted and must be reviewed by a qualified medical professional.'
  };
};


// ======================================================
// EXPORTS
// ======================================================
module.exports = {
  generateDiagnosis
};