// PURPOSE:
// Converts AI detection results into preliminary
// clinical support output for doctor review.
//
// IMPORTANT:
// This is NOT a final medical diagnosis.
// Results must always be reviewed by a qualified doctor.



// Estimate Stone Size from Bounding Box

const estimateStoneSize = (bbox) => {
  if (!bbox) return 0;

  let width  = 0;
  let height = 0;

  // YOLOv8 format — x1,y1,x2,y2
  if (bbox.x1 !== undefined && bbox.x2 !== undefined) {
    width  = Math.abs(bbox.x2 - bbox.x1);
    height = Math.abs(bbox.y2 - bbox.y1);
  }

  // Old format — x,y,width,height
  if (bbox.width !== undefined) {
    width  = Number(bbox.width  || 0);
    height = Number(bbox.height || 0);
  }

  // Approximate size in mm (pixel to mm conversion)
  // Average KUB X-ray pixel spacing ~0.2mm per pixel
  const avgPixels = (width + height) / 2;
  const sizeInMm  = avgPixels * 0.2;

  return Number(sizeInMm.toFixed(1));
};


// Get Risk Level based on size and confidence

const getRiskLevel = (sizeInMm, confidence) => {
  if (sizeInMm <= 0 || confidence <= 0) {
    return 'No Risk';
  }

  // Clinical stone size classification
  if (sizeInMm < 4) {
    return 'Low';      // Small stones — likely pass naturally
  }

  if (sizeInMm >= 4 && sizeInMm < 8) {
    return 'Medium';   // May need medical intervention
  }

  return 'High';       // Large stones — specialist needed
};


// Generate Clinical Recommendation

const getRecommendation = (detected, riskLevel, sizeInMm) => {
  if (!detected) {
    return (
      'No obvious urinary stone was identified by the AI detection model. ' +
      'Clinical correlation and doctor review are recommended.'
    );
  }

  switch (riskLevel) {
    case 'Low':
      return (
        `A small suspicious region (~${sizeInMm}mm) was identified. ` +
        'Clinical review and follow-up observation may be beneficial. ' +
        'Increased fluid intake is generally recommended.'
      );

    case 'Medium':
      return (
        `A possible urinary stone (~${sizeInMm}mm) was identified. ` +
        'Further medical evaluation or imaging review is recommended. ' +
        'Specialist consultation may be required.'
      );

    case 'High':
      return (
        `A large suspicious urinary stone region (~${sizeInMm}mm) was identified. ` +
        'Specialist consultation is strongly recommended. ' +
        'Immediate medical evaluation may be necessary.'
      );

    default:
      return 'Further clinical evaluation is recommended.';
  }
};


// Generate AI Draft Report Text

const generateAIDraft = ({
  detected,
  confidence,
  riskLevel,
  recommendation,
  stoneCount,
  sizeInMm,
}) => {
  const date = new Date().toLocaleDateString('en-GB');

  return `
AI-ASSISTED PRELIMINARY RADIOLOGY REPORT
==================================================
Date of Analysis : ${date}
System           : UroScan AI — Diagnosis Support System

AI DETECTION FINDINGS:
- Detection Status   : ${detected ? '⚠️ Suspicious Stone Detected' : '✅ No Obvious Stone Detected'}
- Detection Confidence: ${confidence}%
- Detected Stone Count: ${stoneCount}
- Estimated Size     : ${sizeInMm > 0 ? `~${sizeInMm} mm` : 'N/A'}
- Risk Level         : ${riskLevel}

AI CLINICAL RECOMMENDATION:
${recommendation}

IMPORTANT DISCLAIMER:
This report is automatically generated by an AI-assisted
urinary stone detection system. It is intended only for
preliminary clinical support purposes.
Final interpretation and diagnosis must be confirmed
by a qualified medical professional.

==================================================
  `.trim();
};


// Main Diagnosis Generator

const generateDiagnosis = (detectionResult) => {
  // No detection case
  if (!detectionResult || detectionResult.detected === false) {
    const riskLevel      = 'No Risk';
    const recommendation = getRecommendation(false, riskLevel, 0);

    return {
      detected:        false,
      confidence:      0,
      estimatedSize:   0,
      stoneCount:      0,
      riskLevel,
      recommendation,
      status:          'no_obvious_stone',
      aiDraft:         generateAIDraft({
        detected:    false,
        confidence:  0,
        riskLevel,
        recommendation,
        stoneCount:  0,
        sizeInMm:    0,
      }),
      disclaimer:
        'This output is AI-assisted and must be reviewed by a qualified medical professional.',
    };
  }

  // Detection exists
  const confidence = Number(
    ((detectionResult.confidence || 0) * 100).toFixed(2)
  );

  const bbox       = detectionResult.bbox  || null;
  const stoneCount = detectionResult.stoneCount || 1;

  // Calculate estimated size
  const sizeInMm = estimateStoneSize(bbox);

  // Get risk level
  const riskLevel = getRiskLevel(sizeInMm, confidence);

  // Get recommendation
  let recommendation = getRecommendation(true, riskLevel, sizeInMm);

  // Low confidence warning
  if (confidence < 60) {
    recommendation +=
      ' Note: Detection confidence is relatively low. ' +
      'Additional clinical review is strongly recommended.';
  }

  // Generate draft text
  const aiDraft = generateAIDraft({
    detected: true,
    confidence,
    riskLevel,
    recommendation,
    stoneCount,
    sizeInMm,
  });

  return {
    detected:      true,
    confidence,
    estimatedSize: sizeInMm,
    stoneCount,
    riskLevel,
    recommendation,
    status:        'pending_doctor_review',
    aiDraft,
    disclaimer:
      'This output is AI-assisted and must be reviewed by a qualified medical professional.',
  };
};

module.exports = { generateDiagnosis };