const Report = require('../models/Report'); 

// 1. AI Draft එක හදන Function එක
exports.createDraftReport = async (req, res) => {
    try {
        const { doctorId, patientName, patientAge, patientGender, imageId, imagePath, yoloResults } = req.body;
        
        // අලුත් YOLOv8 මොඩල් එකෙන් එන stones ගණන හරියටම ගනිමු
        const stoneCount = yoloResults?.detected_objects?.length || 0; 
        const hasStones = stoneCount > 0;

        const date = new Date().toLocaleDateString('en-GB'); // DD/MM/YYYY format එකට

        // වඩාත් වෛද්‍ය විද්‍යාත්මක වාර්තාවක් සැකසීම
        let findingText = hasStones 
            ? `The YOLOv8-v3.0 model identified ${stoneCount} high-density calcifications (stones) within the urinary tract area.` 
            : "Radiographic analysis shows no significant high-density calcifications suggestive of urinary calculi.";

        const aiDraftText = `MEDICAL IMAGING REPORT (AI-ASSISTED PRELIMINARY DRAFT)
==================================================
Date of Analysis: ${date}

PATIENT SUMMARY:
- Name: ${patientName} | Age: ${patientAge} | Gender: ${patientGender}

RADIOLOGICAL FINDINGS (AI):
- Observations: ${findingText}
- Stone Count: ${stoneCount} detected

CLINICAL IMPRESSION:
- ${hasStones ? "Findings highly suggestive of Urolithiasis." : "No obvious urinary stones detected."}

--------------------------------------------------
IMPORTANT: This report is a draft generated by a Single-Class YOLOv8 Object Detection model. 
Final validation by a Radiologist or Medical Officer is mandatory.
==================================================`;

        const newReport = new Report({
            doctor: doctorId,
            patientName,
            patientAge,
            patientGender,
            imageId,
            imagePath,
            aiResult: yoloResults,
            hasStones,
            stoneCount,
            aiDraft: aiDraftText,
            status: 'pending' 
        });

        await newReport.save();
        res.status(201).json({ success: true, message: "Draft Report generated successfully!", reportId: newReport._id });

    } catch (error) {
        console.error("Report Error:", error);
        res.status(500).json({ success: false, error: error.message });
    }
};

// 2. Doctor විසින් රිපෝට් එක Confirm කරන Function එක
exports.confirmReport = async (req, res) => {
    try {
        const reportId = req.params.id;
        const { aiDraft, doctorNotes, status, diagnosis } = req.body;

        const updatedReport = await Report.findByIdAndUpdate(
            reportId,
            { aiDraft, doctorNotes, status, diagnosis },
            { new: true } 
        );

        if (!updatedReport) return res.status(404).json({ success: false, message: "Report not found!" });

        res.status(200).json({ success: true, message: "Report verified!", report: updatedReport });

    } catch (error) {
        console.error("Error confirming report:", error);
        res.status(500).json({ success: false, message: "Server error.", error: error.message });
    }
};

// ==========================================
// 🚀 මේ තියෙන්නේ මැකිලා ගියපු ෆන්ක්ෂන් දෙක
// ==========================================

// 3. Database එකේ තියෙන රිපෝට් ඔක්කොම ගන්න Function එක (Doctor ට පෙන්නන්න)
exports.getAllReports = async (req, res) => {
    try {
        // අලුත්ම රිපෝට් උඩින් එන්න sort කරලා තියෙන්නේ
        const reports = await Report.find().sort({ createdAt: -1 });
        res.status(200).json(reports);
    } catch (error) {
        res.status(500).json({ message: "Error fetching reports", error: error.message });
    }
};

// 4. රෝගියාගේ නමින් රිපෝට් හොයන Function එක
exports.getPatientReports = async (req, res) => {
    try {
        const reports = await Report.find({ patientName: req.params.name }).sort({ createdAt: -1 });
        res.status(200).json(reports);
    } catch (error) {
        res.status(500).json({ message: "Error fetching patient reports", error: error.message });
    }
};